apiVersion: v1
kind: Service
metadata:
  name: live-score-client-service
spec:
  type: NodePort
  selector:
    name: live-score-client
  ports:
  - targetPort: 3030 # Port of the container
    port: 3030  # Port of the service server or cluser port.
    nodePort: 30014 # Port to communicate with external services
